// app/base/layout.tsx
import { BreadcrumbBar } from "@/components/breadcrumb-bar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BaseLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      {/* Breadcrumb container */}
      <div className="max-w-7xl mx-auto px-4">
        <BreadcrumbBar />
      </div>

      {/* Page content container */}
      <section className="max-w-7xl mx-auto px-4 py-4">{children}</section>
    </>
  );
}
